# Generated by Django 5.2.4 on 2025-07-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0002_alter_palindromeentry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palindromeentry',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
